Repository kaiyuanshe/RFC, pull requests merged in 2025-03, with the labels that each got.

#10 [add] GitHub action of Lark notification
  .github/scripts/deno.json
  .github/scripts/transform-message.ts
  .github/workflows/Lark-notification.yml
  README.md
Labels: feature

#11 refactor: modularize GitHub action message transformer
  .github/scripts/transform-message.ts
Labels: enhancement

#9 [optimize] update KaiYuanShe Charter to version 2025
  Charter.md
  README.md
Labels: s3-candidate, feature
